### ISSUE TITLE
Cannot load test.evm

### ISSUE THREAD

**Issue by t4sk** [crytic/ethersplay#49]
I tried to load `test.evm` from examples and I get this error

```
Disallowing the creation of segment @ 0x97 with dataOffset @ 0x97 and length 0x97 which is larger than the parent's length
Added EVM entry point at 0x0
Traceback (most recent call last):
  File "/home/t4sk/bkp/dev/binaryninja/plugins/../python/binaryninja/binaryview.py", line 2023, in _init
    return self.init()
  File "/home/t4sk/.binaryninja/plugins/ethersplay/evm.py", line 443, in init
    scope=SettingsScope.SettingsContextScope
  File "/usr/lib64/python3.7/enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: SettingsContextScope
BinaryView of type 'EVM' failed to initialize!
```

Has anyone else encountered this issue?

**Comment by lzhou1110** [comment]
I had the same issue and indeed changing to updating to `SettingsResourceScope` made this work again.
